### ISSUE TITLE
rcon功能闪退问题

### ISSUE THREAD

**Issue by Milky0811** [hualuoo/palworld-helper#4]
服务端来源：Steamcmd 版本 1.29更新 最新

服务器系统：win11 23H2
RCON为本地服务器127.0.0.1部署，端口默认25575，防火墙已关闭，不管是自动配置rcon还是手动配置rcon，连接rcon后一定会闪退。想知道是为什么

**Comment by hualuoo** [comment]
使用的软件版本是多少

**Comment by Milky0811** [comment]
1.0.8

**Comment by hualuoo** [comment]
闪退可能是RCON密码错误，关闭服务端后，自动配置RCON，再启动服务端，再连接RCON测试一下呢？

**Comment by Milky0811** [comment]
按照你说的做了，依然闪退
![Uploading Screenshot 2024-01-29 145434.png…]()

**Comment by hualuoo** [comment]
没办法看到图片，暂时无法复现该问题，方便的话可以加群联系我，我发个debug版本看看啥问题

**Comment by Milky0811** [comment]
嗯麻烦了，等过段时间吧，暂时还在外地
